services:
  partae:
    image: 'docker.partae'
    command: 'python api/gunicorn_app.py'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: 'partae'
    ports:
      - '5000:5000'
    environment:
      PARTAE_MAX_QUEUE_SIZE: 128
      PARTAE_MODEL_BASE_PATH: <path_to_model_base>
      PARTAE_OUTPUT_BASE_PATH: <path_to_output>
      GUNICORN_RUN_HOST: '0.0.0.0:5000'
      GUNICORN_WORKERS: 1
      GUNICORN_THREADS: 1
      GUNICORN_ACCESSLOG: '-'
    volumes:
      - '<path_to_model_base>:<path_to_model_base>'
      - '<path_to_output>:<path_to_output>'
    networks:
      - pipeline
    shm_size: 512mb
    restart: always